### ISSUE TITLE
Hold down key

### ISSUE THREAD

**Issue by dxwil** [KarsMulder/evsieve#44]
Hi, I have a dedicated brightness button on my laptop and I'm trying to make it function. It shows value 1 on press down and continuously outputs value 2 on hold down. The following is my evsieve command which works when I press down the button but not when I hold it down. What could be the problem here? If I only make evsieve listen to value 2, it still only increases the brightness once, but I want it to be constant until I release.

`sudo evsieve --input /dev/input/event1 --hook key:brightnessdown:1~2 exec-shell="brillo -q -U 5; pkill -SIGRTMIN+9 waybar" --hook key:brightnessup:1~2 exec-shell="brillo -q -A 5; pkill -SIGRTMIN+9 waybar"`

**Comment by KarsMulder** [comment]
This happens because hooks were designed to operate on the current "state" of the keys instead of singular events, so they could accomodate activating on a combination of keys like "ctrl+A".

An obscure corner of the documentation (unfortunately) says the following about hooks:

> Formally said, the hook triggers when (1) an event is received that matches one of the KEYs specified, (2) the last event whose type, code and domain matched that same KEY did not have a value matching that KEY, and (3) for all other KEYs, the last event whose type, code and domain matched those KEYs had a value matching those KEYs.

In short, sending multiple `key::2` events will not trigger the hook again unless a `key::0` event arrives in between.

(And it is "unfortunate" that it says so because it turned out that these semantics are flawed and do not interact nicely with some other systems such as `--withhold`, but those semantics are kept because of backwards compatibility. If I ever release an evsieve 2.0, the semantics are going to be different.)

A somewhat hacky solution to make a hook trigger on every repeat event would be to use a map that turns every event into a press-release event:

```
evsieve --input /dev/input/event1 \
        --map key:brightnessdown:1~2 ::1 ::0 \
        --map key:brightnessup:1~2   ::1 ::0 \
        --hook key:brightnessdown exec-shell="brillo -q -U 5; pkill -SIGRTMIN+9 waybar" \
        --hook key:brightnessup   exec-shell="brillo -q -A 5; pkill -SIGRTMIN+9 waybar"
```

**Comment by dxwil** [comment]
This workaround seems to work now, thanks
